service:
  name: simple-payroll-calculator
  #name: calculator

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  profile: devalex
  stage: devalex
  region: eu-west-1

functions:
  payroll:
    handler: payroll/handler.payroll
    timeout: 5
    events:
      - http:
          method: post
          path: payroll

custom:
  serverless-offline:
    port: 3003