service:
  name: salary-calculator
  #name: calculator

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  profile: devalex
  stage: dev
  region: eu-west-1

functions:
  payroll:
    handler: payroll/handler.payroll
    events:
      - http:
          method: post
          path: payroll